import { words } from '../../../../lang/lang';
import { FillingField } from './FillingField';

export const SectionFilingFields = () => {
  return (
    <section className="credit-card-online-app__container-down-half__fields">
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.lastName.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.lastName.placeHolder
        }
        isRequiredAttribute={true}
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.firstName.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.firstName.placeHolder
        }
        isRequiredAttribute={true}
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.patronymic.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.patronymic.placeHolder
        }
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.select.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.select.placeHolder
        }
        isRequiredAttribute={true}
        type="select"
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.email.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.email.placeHolder
        }
        isRequiredAttribute={true}
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.dateBirth.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.dateBirth.placeHolder
        }
        isRequiredAttribute={true}
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.passportSeries.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.passportSeries.placeHolder
        }
        isRequiredAttribute={true}
      />
      <FillingField
        header={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.passportNumber.header
        }
        placeholder={
          words.loanPage.processGetCreditCard.UK.onlineApplicationCreditCard
            .fillingFields.passportNumber.placeHolder
        }
        isRequiredAttribute={true}
      />
    </section>
  );
};
